-- liquibase formatted sql

-- changeset author:anton.kaklyugin:001-1
CREATE TABLE IF NOT EXISTS public.power_outage_addresses
(
    id                int4 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    message_hash_code int4 NULL,
    created_at        timestamp(6) NULL,
    last_updated_at   timestamp(6) NULL,
    time_off          timestamptz(6) NULL,
    time_on           timestamptz(6) NULL,
    address           varchar(255) NULL,
    city              varchar(255) NULL,
    "comment"         varchar(255) NULL,
    queue_sent_at     timestamptz(6) NULL,
    reason            varchar(255) NULL,
    url               varchar(255) NULL,
    CONSTRAINT power_outage_addresses_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.source_page_urls
(
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    page_url varchar(255) NULL,
    enabled BOOLEAN DEFAULT TRUE,
    last_updated_at timestamp(6) NULL,
    CONSTRAINT source_page_urls_pkey PRIMARY KEY (id),
    CONSTRAINT uk_source_page_urls UNIQUE (page_url)
);

insert into source_page_urls(page_url,enabled, last_updated_at)
values ('https://www.donenergo.ru/grafik-otklyucheniy/52/1/',false, now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/53/1/',false, now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/62/1/',false, now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/64/1/',false, now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/55/1/',false, now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/56/1/',false, now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/59/1/',false, now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/60/1/',true, now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/61/1/',true, now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/57/1/',false, now());