-- liquibase formatted sql

-- changeset author:anton.kaklyugin:001-1
CREATE TABLE IF NOT EXISTS public.power_outage_addresses
(
    id                int4 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    message_hash_code int4 NULL,
    created_at        timestamp(6) NULL,
    last_updated_at   timestamp(6) NULL,
    time_off          timestamptz(6) NULL,
    time_on           timestamptz(6) NULL,
    address           varchar(255) NULL,
    city              varchar(255) NULL,
    "comment"         varchar(255) NULL,
    reason            varchar(255) NULL,
    url               varchar(255) NULL,
    CONSTRAINT power_outage_addresses_pkey PRIMARY KEY (id)
);

-- changeset author:anton.kaklyugin:001-2
CREATE TABLE IF NOT EXISTS public.power_outage_source_pages
(
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    last_updated_at timestamp(6) NULL,
    page_url varchar(255) NULL,
    CONSTRAINT power_outage_source_pages_pkey PRIMARY KEY (id)
);

-- changeset author:anton.kaklyugin:001-3
insert into power_outage_source_pages(page_url, last_updated_at)
values ('https://www.donenergo.ru/grafik-otklyucheniy/52/1/', now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/53/1/', now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/62/1/', now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/64/1/', now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/55/1/', now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/56/1/', now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/59/1/', now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/60/1/', now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/61/1/', now()),
       ('https://www.donenergo.ru/grafik-otklyucheniy/57/1/', now());