name: Local Build and Deploy
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Bot Docker Image
        run: docker build -t bot ./telegram-app

      - name: Build Crawler Docker Image
        run: docker build -t crawler ./crawler-app
      
      - name: Deploy with local config
        run: |
          docker compose \
            -f /home/deploy-user/.bot_config/docker-compose.yml \            
            up -d --build --remove-orphans